### ISSUE TITLE
Provide a simpler way to create an array of a specific type of items

### ISSUE THREAD

**Issue by phillipskevin** [canjs/can-observable-array#35]
It is often useful to create an array where every item is a specific type. With `can-define` you could do something like this:

```js
const VM = DefineMap.extend({
  todos: [ Todo ]
});
```

...which was a shorthand for

```js
const TodoList = DefineList.extend({
  "#": Todo
});

const VM = DefineMap.extend({
  todos: TodoList
});
```

We should make it easier to do this with `DefineArray`. I propose a static `of` method for this:

```js
class VM extends DefineObject {
  static define = {
    todos: DefineArray.of(Todo)
  };
}
```

**Comment by justinbmeyer** [comment]
## Lists of a type (shorthand)

- 
- ? Should this do convert?

```js
static props = { people: type.convert(ObservableArray.of(type.convert(Person)) }
```

If this is designed for models:

```js
Todo extends ObservableObject {
  static props = {};
}
TodoList extend ObservableArray {
  static items = type.convert(Todo);
}

TodoList = ObsableArray.of( type.convert(Todo) );
```



- `people: ObservableArray.Convert.of(Person.Convert)`


aside:

```
props = {
  items: convert( ObservableArray )
}


obj.items = null; // what does this do?
```

## Recursive Types 

```
class A {
  
}

class Folder extends ObservableArray {
  props = { // stick in getter?
    subfolder: ObservableArray.of(Folder) 
  }
}
```

## Deep Types


```
static props = {
  data: DeepObservable
};

data: MaybeConvertToObservableArrayorObject


...


new Class({data: {foo: "bar", deep: {}})
```

**Comment by matthewp** [comment]
# ObservableArray.of

I think there are two options here:

## ObservableModel

I think the reason use-case here is for models. Models need to convert raw data coming from a web service. The same issue exists within ObservableObject, which defaults to strict properties.

So why not create a type that make good defaults for models? It could:

1. Automatically create an array type so you don't have to.
2. Default all properties to convert.
3. Automatically integrates with `can-rest-model` or something else?

This seems like a pretty large change, however.

## ObservableArray[name]

The quickest/smallest change would be to just create an `.of` that defaults to converting. There is one problem though, [Array.of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/of) exists, and does something much different. So might need a different name.

**Comment by justinbmeyer** [comment]
## Use Cases

I think there are two main use cases:

- inline types
- making model list types easier 

### Inline types 

As Kevin noted above, it's fairly common to want to specify an observable array of a particular type on your view model.  Currently, you'd do it as a "side" class as follows:

```
class Rounds extends ObservableArray {
  static items = type.convert(Game);
}

class StacheElement {
  static props = {
    roundOneGames: type.convert(Rounds)
  }
}
```

Ideally, we'd have a shorthand:

```js
class StacheElement {
  static props = {
    roundOneGames: ObservableArray.thatConvertsTo(Game)
  }
}
```

### Model list types 

Currently, can-connect expects a `List` type.  It most of our guides, we create show creating them:

```
class Todo extends ObservableObject {}

class TodoList extends ObservableArray {
  static items = Todo;
}
```

It would be nice to not have to show all of that.  

__NOTE__: Model list types might be considered a subset of the _Inline types_ problem

## Ideas 

### ObservableArray.thatConvertsTo(Type)

Instead of `.of()` we could use `ObservableArray.thatConvertsTo(Type)`. This reads pretty well.

Do we make this convert `[]` to an ObservableArray?

### ObservableObject includes an array type 

`CanMap` would create a `List` type:

```js
Todo = CanMap.extend({})

Todo.List //-> Constructor

var todos = new Todo.List([{}])
todos[0] instanceof Todo //-> true
```

We could do something similar for `ObservableObject`:

```js
class Todo extends ObservableObject {}

Todo.Array //-> Constructor

var todos = new Todo.Array([{}])
todos[0] instanceof Todo //-> true
```

This might be as easy as a static getter:

```js
static get List(){
 var RecordType = this;
  // need to cache the List type for this type
  this.List = class extends ObservableArray {
    static items = RecordType
  }
}
```

**Comment by matthewp** [comment]
ObservableArray.thatConvertsTo is fine with me. I don't think you're saving much vs writing `class extends ObservableArray { static items = type.convert(Game) }` but if you feel strongly about it, I don't think it hurts anything.

My concern would be if we then needed to add a ObservableArray.thatMaybeConvertsTo, and ObservableArray.thatMaybeStrictTo, etc.

**Comment by matthewp** [comment]
# Special Types

This covers 3 new type that have special behavior. One derives from user defined types, and the other two do not.

## Converting list type shorthand

@justinbmeyer wants a shorthand for creating converting list types without needing to use JavaScript `extend` and specifying the `static items` field. The proposal there is `ObservableArray.thatConvertsTo(Type)`. Example:

```js
class Faves extends ObservableObject {}

const EveryonesFaves = ObservableArray.thatConvertsTo(Faves);
```

## Self-referencing type

After thinking about this one a lot I don't think it's really possible. We could come up with something, whether that be `type.Identity` or a special token like `type: "^"` but it breaks down when you need to use it in list, which is the case of the `Folder` use case:

```js
class Folder extends ObservableObject {
  static props = {
    subfolders: ObservableArray.thatConvertsTo(type.Identity)
  };
}
```

Here, a converting type is created, but unfortunately it cannot know what `type.Identity` refers to. So this doesn't work.

So I think we should punt on this problem until a good solution comes around. You can fill the need with a setter:

```js
class Folder extends ObservableObject {
  static props = {
    subfolders: {
      set(val) {
        return new ObservableArray(val.map(props => new Folder(props)));
      }
    }
  };
}
```

## Deep/recursive observables

The user case here is to take an arbitrarily nested object with unknown keys and make the entire thing observable. This often comes from some 3rd party service/library that is being used where you do not have control over the props.

```js
import { UndecidedObservable } from "can";

let obj = new UndecidedObservable({
	inner: {
		prop: "A"
	}
});

obj.inner.on("prop", function(ev, newVal) {
	assert.equal(newVal, "B", "changed values");
});

obj.inner.prop = "B";
```

We just need to decide on the name which comes down to :

* __RecursiveObservable__
* __DeepObservable__

**Comment by justinbmeyer** [comment]
```js

class MetaTag extends ObservableObject {}

class Folder extends ObservableObject {
    static props = {

        // + solves most common case 
        // + it is a function, not using any special syntax right now 
        // + Makes Model's List type easy 
        metaTags: ObservableArray.convertsTo(MetaTag);
        

        // + easy to remember 
        // - takes up special syntax 
        // - have you remember convert 
        // - should this work directly as a prop definition?
        metaTags: {type: [type.convert(MetaTag)]}
        metaTags: [type.convert(MetaTag)]

        // + easy to remember 
        // - should this work directly as a prop definition?
        // - converts without convert ... nothing else does this ...
        // + allows for other inline types in the future
        metaTags: {type: [MetaTag]}


        address: {
            type: ObservableObject.convertsTo({
                street: String,
                city: String,
                zipcode: Number
            })
        }
        
    };
}
```

**Comment by matthewp** [comment]
# Special types

This covers 3 new types that cover edge cases that are not easily expressed with the current type system and the latest possible solutions:

## "Inline" type shorthand

In order to avoid creating a lot of single-use types, we would like it to be possible to define types according to their "shape". This presents 2 possible solutions:

### Shape based typing

In this case, you define types using bracket notation, `[` arrays and curly braces, `{` for objects, defining their shape:

```js
class Faves extends ObservableObject {
  static props = {
    colors: [Color],

    band: {
      name: String,
      genre: Genre
    }
  };
}
```

In the above example a new type is created for `colors` and `bands`.

* __+__: Minimal syntax required.
* __-__: Special case for type definitions.
* __-__: What if we want to allow defining arrays/objects as defaults.

### ObservableArray.convertsTo

In this option a new derived Array type is created that essentially acts as a shorthand for `static items = Type`. Since converting is the primary use-case only `convertsTo` is implemented and not others.

```js
class Faves extends ObservableObject {
  static props = {
    colors: ObservableArray.convertsTo(Color),

    band: ObservableObject.convertsTo({
      name: String,
      genre: Genre
    })
  };
}
```

Note that `convertsTo` is being used as it works equally well with Objects and Arrays.

## Late binding types

This refers to referencing bindings that do not exist yet. There are two primary cases where this might occur:

1. Self-reference; meaning creating a property that is the same type as the other Type.
1. Referencing a type that is later defined in the same JavaScript module; usually because that Type refers back to the first (and therefore creates a cycle).

Options here are:

```js
class Folder extends ObservableObject {
  static props = {
    subfolder: type.late(() => Folder)
  };
}
```

This builds a new `type.late` function that results the typing later (probably the first time `getSchema` is called). This allows refering to bindings not yet defined.

Second option is:

```js
class Folder extends ObservableObject {
  static props = {
    subfolder: {
      [Symbol.for('can.new')](props) {
        return new Folder(props);
      }
    }
  };
}
```

This already works today. This is shown just for the sake of comparison; does the sugar of the first option warrant implementing.

## Deep / recursive observables

The user case here is to take an arbitrarily nested object with unknown keys and make the entire thing observable. This often comes from some 3rd party service/library that is being used where you do not have control over the props.

```js
import { UndecidedObservable } from "can";

let obj = new UndecidedObservable({
	inner: {
		prop: "A"
	}
});

obj.inner.on("prop", function(ev, newVal) {
	assert.equal(newVal, "B", "changed values");
});

obj.inner.prop = "B";
```

We just need to decide on the name which comes down to :

* __RecursiveObservable__
* __DeepObservable__

**Comment by justinbmeyer** [comment]
Shapes directly as property definitions might be confusing with default values (prop: [Type] vs numbers: [1,2,3]). Might need to stick them under “type:” (prop: {type: [Type]})

**Comment by matthewp** [comment]
## type.late issues

1. Where should the unwrapping occur?
  1. If in can-observable-mixin, how can you use `type.late` outside of classes that derive from that?
1. Should this work? `type.late(() => String)` as a strict type? `can-type`doesn't currently control that `String` is the same as `type.check(String)`. Should it now?

**Comment by matthewp** [comment]
Closing in favor of the specific issues.
